# Project-wide Gradle settings.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html

# Specifies the JVM arguments used for the Gradle Daemon.
# Same as setting JVM arguments on the command line: -Xmx4g -XX:MaxMetaspaceSize=512m
org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8

# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects.
org.gradle.parallel=true

# Enables the configuration cache for faster builds.
org.gradle.configuration-cache=true

# AndroidX background
android.useAndroidX=true

# Enables non-transitive R classes for faster builds.
android.nonTransitiveRClass=true

# Disables Jetifier since all dependencies are already AndroidX.
android.enableJetifier=false
