[versions]
agp = "9.2.1"
kotlin = "2.4.0"
coreKtx = "1.19.0"
activityCompose = "1.13.0"
composeBom = "2026.06.00"
composeMaterial3 = "1.5.0-alpha22"
coilCompose = "3.5.0"
litertlm = "0.13.1"
lifecycle = "2.9.1"
markdownRenderer = "0.43.0"
koog = "1.0.0"
koogLitert = "1.0.0-beta"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "composeMaterial3" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilCompose" }
coil-network = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coilCompose" }
litertlm = { module = "com.google.ai.edge.litertlm:litertlm-android", version.ref = "litertlm" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
markdown-renderer-m3 = { module = "com.mikepenz:multiplatform-markdown-renderer-m3", version.ref = "markdownRenderer" }
koog-agents-core = { module = "ai.koog:agents-core", version.ref = "koog" }
koog-litert = { module = "ai.koog:prompt-executor-litert-client", version.ref = "koogLitert" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
